import type { Metadata } from "next";
import { Inter, Public_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Link from "next/link";

const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={publicSans.className}>
        <Header />

        {children}

        <Footer />

        <div className="bg-dark-blue px-4 py-4">
          <div className="mx-auto flex max-w-container flex-col gap-1 text-center text-xs text-neutral-200 lg:text-left">
            <span>
              Challenge by{" "}
              <Link
                href="https://www.frontendmentor.io?ref=challenge"
                target="_blank"
              >
                Frontend Mentor
              </Link>
              .
            </span>{" "}
            <span>
              Coded by{" "}
              <Link href="https://github.com/pedroosz" target="_blank">
                Pedro Paulo
              </Link>
              .
            </span>
          </div>
        </div>
      </body>
    </html>
  );
}
